name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Install EB CLI
      - name: Install Elastic Beanstalk CLI
        run: |
          pip install awsebcli

      # Step 4: Deploy the application
      - name: Deploy to Elastic Beanstalk
        run: |
          eb init -p python-3.7 cmtr-740mo2tq-app --region us-east-1
          eb deploy cmtr-740mo2tq-env
